[project]
name = 'project'
requires-python = "==3.13.7"
version = '0'
dependencies = ['httpx==0.28.1', 'pydantic==2.12.3']

[tool.uv]
package = false

[tool.ruff.lint]
extend-select = ['I']
